### ISSUE TITLE
Add a Screenshot

### ISSUE THREAD

**Issue by wtfbbqhax** [HiRoS-neko/ShadeSmear-Themes-Visual-Studio#1]
Can you add a screenshot to your README and Marketplace page so we can preview the look. 

https://marketplace.visualstudio.com/items?itemName=kyle-giammarco.ShadeSmear-Themes

**Comment by HiRoS-neko** [comment]
I have added screenshots to the GitHub repo and the marketplace listing.
Thank you for your interest in the theme.
